### ISSUE TITLE
Can not activate plugins

### ISSUE THREAD

**Issue by ghost** [cardoso/errbot-rocketchat#11]
Hi, I try to install errbot with rocketchat and after use to stackstorm with plugin err-stackstorm.

Rocketchat 0.65.1
Python 3.6.7
Errbot?? when I use command !about:

This is Errbot version 0.1.0 GIT CHECKOUT

* Visit http://errbot.io/ for more information about errbot in general.
* Visit http://errbot.io/en/latest/#user-guide for help with configuration,
administration and plugin development.

Errbot is built through the hard work and dedication of everyone who
contributes code, documentation and bug reports at https://github.com/errbotio
but a special thank you should be given to Guillaume Binet, Tali Petrover,
Ben van Daele, Paul Labedan and others at Mondial Telecom, the birthplace of
Errbot, without whom this project never would have grown into what it is today.
errbot.io
Errbot — Err 5.1.3 documentation
A Python chatbot with a rich and friendly API and an emphasis on developer productivity
errbot.io
Errbot — Err 5.1.3 documentation
A Python chatbot with a rich and friendly API and an emphasis on developer productivity

### I could connect errbot with rocketchat but when I try activate plugin Webserver I get the following message:

`!plugin config Webserver {'HOST': '0.0.0.0', 'PORT': 3141,
'SSL': {'enabled': False, 'host': '0.0.0.0', 'port': 3142, 'certificate': '', 'key': ''}}`

`Unknown plugin or the plugin could not load Webserver.`

`!status plugin`

`## Yes I am alive...`
### Plugins
Status | Name 
------- | ----------------------- 
*A*{:color='green'} | ACLs
*A*{:color='green'} | Backup
*D* | ChatRoom
*D* | CommandNotFoundFilter
*D* | Flows
*A*{:color='green'} | Health
*A*{:color='green'} | Help
*A*{:color='green'} | Plugins
*D* | TextCmds
*A*{:color='green'} | Utils
*D* | VersionChecker
*D* | Webserver
*A*{:color='green'} = Activated, *D* = Deactivated, *B*{:color='red'} = Blacklisted, *C*{:color='yellow'} = Needs to be configured
Load 1.05, 1.09, 0.99
GC 0->305 1->3 2->10`

`!plugin activate Webserver`

`Webserver isn't a valid plugin name. The current plugins are:`
`- Backup`
`- Health`
`- Help`
`- Plugins`
`- Utils`
`- ACLs`

Log

`09:20:10 DEBUG    errbot.core               *** text = !plugin activate Webserver
09:20:10 DEBUG    errbot.plugins.ACLs       Check plugin_activate for ACLs.
09:20:10 INFO     errbot.plugins.ACLs       Matching ACL {} against username iperez for command Plugins:plugin_activate.
09:20:10 INFO     errbot.plugins.ACLs       Check if plugin_activate is admin only command.
09:20:10 INFO     errbot.core               Processing command "plugin_activate" with parameters "Webserver" from iperez
09:20:10 DEBUG    errbot.flow               Test if the command plugin_activate is a trigger for an inflight flow ...
09:20:10 DEBUG    errbot.flow               None matched.`

**Comment by ghost** [comment]
I can activate plugin Webserver and configured.

I put the plugin Webserver in config.py

`CORE_PLUGINS = ('ACLs', 'Backup', 'Health', 'Help', 'Plugins', 'Utils', 'Webserver')`

But now can not install err-stackstorm and get the follow error

`Installing` https://github.com/fmnisme/err-stackstorm.git...`
`Some plugins are generating errors:`
`<class 'subprocess.CalledProcessError'>: Command '['pip', 'install', '--user', '--requirement',` `'./bot_data/plugins/fmnisme/err-stackstorm/requirements.txt']' died with <Signals.SIGSEGV: 11>.`
`File "/home/ivan/.local/lib/python3.6/site-packages/errbot/plugin_manager.py", line 79, in` `install_packages`
`subprocess.check_call(['pip', 'install', '--user', '--requirement', req_path])`
`File "/usr/lib/python3.6/subprocess.py", line 291, in check_call`
`raise CalledProcessError(retcode, cmd)`

`Removing ./bot_data/plugins/fmnisme/err-stackstorm as it did not load correctly.`
`Plugins reloaded.`

**Comment by ghost** [comment]
Follow this on https://github.com/fmnisme/err-stackstorm/issues/30

**Comment by nzlosh** [comment]
What version of errbot are you running?  You should be able to find the actual version by going to the errbot installation directory running this command
```
# find -iname 'version.py' | grep errbot | xargs -n 1 grep VERSION
VERSION = '5.2.0'
VERSION = '5.2.0'
```
