### ISSUE TITLE
error at python -m errbot.cli with RC 6.1

### ISSUE THREAD

**Issue by rzemykers** [cardoso/errbot-rocketchat#4]
RC 6.1
Errbot 4.3.4
Python 3.5

At first step I have checked traffic beetwen server but 0 packets was sent from errbot server to RC.

> 18:09:46 ERROR    aoikrocketchaterrbot      # ----- `serve_once` failed with error -----
Traceback (most recent call last):
  File "/root/errbot-rocketchat/src/aoikrocketchaterrbot/backends/aoikrocketchaterrbot.py", line 621, in serve_forever
    self.serve_once()
  File "/root/errbot-rocketchat/src/aoikrocketchaterrbot/backends/aoikrocketchaterrbot.py", line 701, in serve_once
    self._meteor_client.on('connected', self._meteor_connected_callback)
  File "/usr/lib/python3.5/site-packages/pyee-5.0.0-py3.5.egg/pyee/__init__.py", line 120, in on
    return _on(f)
  File "/usr/lib/python3.5/site-packages/pyee-5.0.0-py3.5.egg/pyee/__init__.py", line 114, in _on
    self._add_event_handler(event, f, f)
  File "/usr/lib/python3.5/site-packages/pyee-5.0.0-py3.5.egg/pyee/__init__.py", line 130, in _add_event_handler
    self._events[event][k] = v
TypeError: unhashable type: 'AoikRocketChatErrbot'

**Comment by cardoso** [comment]
Thanks @przemika 

I'll take a look as soon as I can. Let me know if you discover anything.

**Comment by rzemykers** [comment]
It's the same on windows server 2016 with python 3.6 and errbot 5.1.3. At first scenerio I used Centos.
I'm not sure I'm doing everything correct.

**Comment by kstevenard** [comment]
trying also to get it working, i faced the same issue. It seems that the backend class (AoikRocketChatErrbot) should contain something like 
```
    def __hash__(self):
        return 0  # this is a singleton anyway
```
This snippet of code comes from the slack backend.
It suppress me the error, but still not able to connect ... will keep you updated in case i'm succeeding

**Comment by cardoso** [comment]
Thank you!! @kstevenard 

I don't have much time lately to maintain this repository, so if you are able to find a solution and the problem is in this project's code, please send a PR. 👍

**Comment by kstevenard** [comment]
i will spend a bit more time in coming days to also support richer message formatting

**Comment by nicoddemus** [comment]
Opened #5 which fixes the backend for us. 👍
