### ISSUE TITLE
Updated README with systemd file

### ISSUE THREAD

**Issue by torgeirl** [cardoso/errbot-rocketchat#6]
Hi @cardoso,

Let me start by thank you for taking over when the original maintainer became inactive. The backend has a few minor issues, but it's mostly functionally and hopefully it will find its way into the official Errbot release down the line.

I've a few minor suggestions for updated to the README, and hope it's OK I address them in a PR.

**Comment by nicoddemus** [comment]
Can this be closed now that #7 has been merged?

**Comment by torgeirl** [comment]
@nicoddemus: yeah, my bad. I'll make another issue if a future PR needs discussion (ie, I started looking into adding `send_card()` support).

**Comment by cardoso** [comment]
I invited you to be a collaborator @torgeirl . That should make things easier 🙂
